modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/therealm18/oc2r-library/issues"
license = "MIT"

[[mods]]
modId = "oc2rlibrary"
version = "${file.jarVersion}"
displayName = "OC2R Library"
authors = "The Realm 18 Studios"
description = '''
OC2R Languages Addon.
'''

[[dependencies.oc2rlibrary]]
modId = "forge"
mandatory = true
versionRange = "[40.4.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.oc2rlibrary]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.oc2rlibrary]]
modId = "oc2r"
mandatory = true
versionRange = "[2.2.4,)"
side = "BOTH"
ordering = "AFTER"
